# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
City.destroy_all
Activity.destroy_all

ActiveRecord::Base.connection.tables.each do |t|
    ActiveRecord::Base.connection.reset_pk_sequence!(t)
end

conrad = User.create(name:'Conrad', city:'Tampa', user_photo:'http://stevensegallery.com/200/300')
city = City.create(name: 'Atlanta', photo_url:'http://vnews.agency/uploads/posts/2015-12/1450082583_atlanta5.jpg', summary: 'Atlanta is the capital of the U.S. state of Georgia. It played an important part in both the Civil War and the 1960s Civil Rights Movement.', latitude:'33.7490', longitude:'84.3880', state:'Georgia', country:'US', population:'472,522')

activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
comment = Comment.create(user_id: conrad.id, activity_id: activity.id, body: 'We went to Childrens Museum of Atlanta in the month of December and had a great outdoor experience, the skyline looked like a lot of fun as well.')

activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
comment = Comment.create(user_id: conrad.id, activity_id: activity.id, body: 'We went to Stone Mountain in the month of December and had a great outdoor experience, the skyline looked like a lot of fun as well.')

activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
comment = Comment.create(user_id: conrad.id, activity_id: activity.id, body: 'We went to Stone Mountain in the month of December and had a great outdoor experience, the skyline looked like a lot of fun as well.')

stone = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
comment = Comment.create(user_id: conrad.id, activity_id: stone.id, body: 'We went to Stone Mountain in the month of December and had a great outdoor experience, the skyline looked like a lot of fun as well.')




city = City.create(name: 'New York City', photo_url:'https://c2.staticflickr.com/4/3513/4049957908_9e02b150c7_b.jpg', summary: 'Atlanta is the capital of the U.S. state of Georgia. It played an important part in both the Civil War and the 1960s Civil Rights Movement.', latitude:'33.7490', longitude:'84.3880', state:'Georgia', country:'US', population:'472,522')
activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')

city = City.create(name: 'Washington D.C', photo_url:'http://vnews.agency/uploads/posts/2015-12/1450082583_atlanta5.jpg', summary: 'Atlanta is the capital of the U.S. state of Georgia. It played an important part in both the Civil War and the 1960s Civil Rights Movement.', latitude:'33.7490', longitude:'84.3880', state:'Georgia', country:'US', population:'472,522')
activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')

city = City.create(name: 'Chicago', photo_url:'https://c1.staticflickr.com/3/2842/33596094080_35e400828d_b.jpg', summary: 'Chicago is renowned for its museums, including the Art Institute of Chicago with its noted Impressionist and Post-Impressionist works.', latitude:'41.8781', longitude:'87.6298', state:'Illinois', country:'US', population:'2.705')
activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')

city = City.create(name: 'Orlando', photo_url:'https://pbs.twimg.com/media/CQ_6eCfWIAADcoF.png', summary: 'Orlando, a city in central Florida, is home to more than a dozen theme parks.', latitude:'28.5383', longitude:'81.3792', state:'Florida', country:'US', population:'277,173')
activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')

city = City.create(name: 'Minneapolis', photo_url:'http://stmedia.startribune.com/images/ows_147652947711815.jpg', summary: 'Minneapolis is a major city in Minnesota that forms "Twin Cities" with the neighboring state capital of St. Paul.', latitude:'44.9778', longitude:'93.2650', state:'Minnesota', country:'US', population:'413,651')
activity = Activity.create(city: city, name:'Childrens Museum of Atlanta', photo_url:'https://res.cloudinary.com/mommy-nearest/image/upload/c_fill,h_450,w_800/wzxholb9gni0px8akqls.jpg', activity_type:'indoor museum', summary:'The Childrens Museum of Atlanta is a childrens museum located in Atlanta, Georgia.', age_requirement:'0-8', admission_cost:'15.95 per adult and child Under 1: free')
activity = Activity.create(city: city, name:'Georgia Aquarium', photo_url:'https://wwcdn.weddingwire.com/vendor/970001_975000/971620/thumbnails/800x800_1494259929389-oceans-ballroom-reception.jpg', activity_type:'indoor aquarium', summary:'The Georgia Aquarium is a public aquarium in Atlanta, Georgia, USA. It houses more than a hundred thousand animals and represents several thousand species, all of which reside in 10 million US gallons of marine and salt water.', age_requirement:'none', admission_cost:'Average cost 30.00 per admission')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
activity = Activity.create(city: city, name:'Stone Mountain Park', photo_url:'http://momvoyage.hilton.com/wp-content/uploads/2014/01/IMG_5289-940x564.jpg', activity_type:'outdoor', summary:'Vast, scenic park with activities, golf, lodging & a cable car ride to a historic, carved peak..', age_requirement:'none', admission_cost:'50.00 for all access per adult and child')
